### PR TITLE
TEST: (Un)Assign an existing topic from/to an item

### PR DESCRIPTION
**Pull request by CorentinLthr-old**
## Content

This contribution includes Cucumber scenarios and Capybara tests for features #32 and #34.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ ] corresponds to a contribution that should be notified to users,
    - [ ] does not generate new errors or warnings at compile or test time,
    - [ ] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [ ] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [ ] be followed by a colon (`:`) with one space after and no space before,
    - [ ] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [ ] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [ ] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [ ] related to this very contribution (feature, fix...),
    - [ ] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [ ] without any typo in variable, class or function names,
    - [ ] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Comment by CorentinLthr-old** [comment]
@benel 
Some scenarios — and not only those I want to add — seem to be randomly passing or failing. 
I ran the same series of tests several times, both locally and on Travis, and got different results, including 100% success twice ... 
I've temporarily changed the `npm test` command in this commit to get more details during the build on Travis. I'll amend this commit later to set the configuration back to what it was.
Do you have an idea about what's going on?

**Comment by benel** [comment]
> Do you have an idea about what's going on?

Try to replace Capybara timeouts (in all three files) with 30 seconds.

**Comment by CorentinLthr-old** [comment]
Thanks, I think it fixed it partially: all tests pass each time now locally, they don't pass on Travis though ... 
It seems that Travis fails when I try to interact with the DOM using an `:xpath` selector, but I don't really know what to change since all tests pass on my machine ... 
Here is a [link](https://travis-ci.org/Hypertopic/Porphyry/builds/396472945) to a detailed build that failed on Travis. The second scenario obviously fails because it tries to delete the topic added in the first failing scenario: the element to be deleted is not created, thus can't be found.

**Comment by benel** [comment]
Maybe a different version of gems or settings... I don't know.

I suppose converting your xPath into a CSS path will be easier than tweaking Travis:
https://ghostinspector.com/docs/css-xpath-conversion/

**Comment by CorentinLthr-old** [comment]
Thanks for your suggestion: I converted all my `:xpath` selectors to `:css` selectors and managed to get the tests to work! But again, they pass on my machine but not on Travis ... 
Here is a [link](https://travis-ci.org/Hypertopic/Porphyry/builds/396825674?utm_source=github_status&utm_medium=notification) to the last detailed failed build. It seems that Travis doesn't find the `input` text field, even though the required package to use it is in the `package.json` file ...
If you have another idea or need me to edit this commit, please tell me, thanks!

**Pull request closed without merging**
