### PR TITLE
FIX: #143 - Add a resource to an item as a link

### PR DESCRIPTION
**Pull request by Ciyax**
## Content

FIX: #143 - Add a resource to an item as a link
Replace simple "split" by a "match" which consider ":" in a link

Fixes #143
---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [X] corresponds to a contribution that should be notified to users,
    - [X] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [X] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `TEST` when it concerns an acceptance test,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [X] be followed by a colon (`:`) with one space after and no space before,
    - [X] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [X] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [X] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [X] related to this very contribution (feature, fix...),
    - [X] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [X] without any typo in variable, class or function names,
    - [X] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Comment by Ciyax** [comment]
J'avais déjà fait une précédente contribution mais mon entrepôt était corrompue et je n'avais pas refait la contribution avant de faire le TP d'aujourd'hui.

**Comment by benel** [comment]
Le contenu est bon. Si vous voulez que l'historique suive les règles, fusionnez les deux commits (en effet le premier déclare résoudre le problème alors que c'est le second qui le fait). Ainsi votre commit aura à la fois la correction et le test correspondant.

**Comment by Ciyax** [comment]
Voila j'ai donc normalement fusionné les deux commit précédent avec un git rebase -i HEAD~2 (en ne conservant que ce qui était utile)

**Comment by benel** [comment]
> Voila j'ai donc normalement fusionné les deux commit précédent avec un git rebase -i HEAD~2 (en ne conservant que ce qui était utile)

Il y a effectivement plusieurs manières de faire. La méthode vue en cours par exemple est de faire un "git reset --soft" (sur le commit à garder) puis à le modifier avec "git commit --amend" (précédé de `git add`).

**Comment by benel** [comment]
Vu.

**Pull request closed without merging**
