### PR TITLE
SCENARIO: Browse items while moving in a physical space (see #369)

### PR DESCRIPTION
**Pull request by albertelombo**
Co-Authored-By: Quentin HAINOS @qhainos
Co-Authored-By: Albert ELOMBO @albertelombo

## Content

This is the scenario designed for browsing items in the edifice. 

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Comment by albertelombo** [comment]
@benel 
Bonjour Monsieur,
Voici notre pull request par rapport au scénario #369  
Qu'en pensez-vous?

Contributeurs : 
- Quentin HAINOS @qhainos 
- Albert ELOMBO @albertelombo

**Review by benel — CHANGES_REQUESTED** [review]
@albertelombo @qhainos

C'est presque bon. 
Il y a juste un problème avec les co-auteurs : 
- inutile de mentionner le _commiter_ comme co-auteur (il est déjà auteur),
- à la suite du nom complet c'est l'_e-mail_  connu de GitHub qui doit être indiqué (et non le login) et il doit être entre "chevrons" (`<>`).

C'est à ce moment-là que vous verrez sur GitHub un petits avatar pour le co-auteur.

**Comment by albertelombo** [comment]
@benel 
Bonjour Monsieur, 
J'ai réécrit mon commit et je l'ai push.
Qu'en pensez-vous? 
Faudrait-il que je fasse une nouvelle pull request?

**Comment by benel** [comment]
Merci @albertelombo.

> Faudrait-il que je fasse une nouvelle pull request?

Non, mais il faudrait tout remettre dans un seul commit. Vous voyez comment faire ?

Par ailleurs, comme il va s'agir d'une réécriture de l'historique, vous devrez "forcer" le "push".

**Comment by albertelombo** [comment]
@benel 
Bonjour monsieur,
J'ai effectué les modifications demandées. Vous conviennent-elles?

**Review by benel — APPROVED** [review]
🎉

**Pull request merged**
