### PR TITLE
Refactor outliner

### PR DESCRIPTION
**Pull request by franck-eyraud**
Outliner refactoring by removing use of `react-ui-tree` component, and provide a tree manipulation class that directly works on Hypertopic topic structure.

Currently implements features #136, #137, #138.

Also comes with the merge of pending Pull Requests #144, #145 and #146.

### CODE REVIEW

**Comment by benel** [comment]
Do you have any idea why automatic tests failed?
Don't worry if you don't, I will try to find why.

**Comment by benel** [comment]
Hmm. It might be because the stain glass originally named "ABT" (and used in tests) was renamed "James Bond" on the test server.

**Comment by franck-eyraud** [comment]
I'm not sure. I didn't know that the tests were failing, but I had a look at the details and the functional tests seem to pass, it just seems that `npm run build` command fails because of React compilation warnings. They shouldn't harm for testing the features, I will fix them as soon as I find some time.

**Comment by benel** [comment]
I fixed data on the test server.

And yes, it seems that warnings are now treated as errors on Travis.

**Comment by benel** [comment]
Here are several fixes that would be needed for the outliner:
- [x] A single `ENTER` should both validate the current row (to create or rename a topic) and display the textbox for a sibling,
- [x] the border of the textbox should be hidden to let the user thinks s•he is literally writing on the page,
- [x] `TAB` should promote the topic rather than setting the focus to the browser address bar (bug found on Firefox, Safari and Chrome in macOS) [`preventDefault` ?],
- [x] `SHIFT-TAB` should demote the topic instead of resetting the name [`preventDefault` ?],
- [x] `BACKSPACE` should be usable as an alternate to `DEL` for mac users with no `DEL` keys (`preventDefault` will be needed since Firefox use it as a shortcut to `back`),
- [x] Fix the creation of the first topic on a new viewpoint or on a viewpoint without topics (I still cannot manage to do it). A way could be to use the viewpoint name as a row similar to a topic.

**Comment by franck-eyraud** [comment]
Thank you for the feedback, I made some of the changes, and the tests now pass.

**Comment by benel** [comment]
Great!

**Comment by benel** [comment]
I don't know if it is related to your commits, but when I test this PR and use it for real, I get several exceptions on refresh:

- [ ] "Unhandled Rejection (TypeError): undefined is not an object (evaluating 'viewpoint.id = v.id')" src/components/Portfolio/Portfolio.jsx:180
- [ ] "Unhandled Rejection (TypeError): undefined is not an object (evaluating 'data[params.corpus][params.item]')" src/components/Item/Item.jsx:152

**Comment by franck-eyraud** [comment]
> Here are several fixes that would be needed for the outliner:

All the points should now be fixed, let me know what do you think

> when I test this PR and use it for real, I get several exceptions on refresh:

What do you mean "for real" ? Do you have some example of data that makes it crash ? 

> I don't know if it is related to your commits

Maybe not, did you also check with a previous version ? The messages look like what we had in LaSuli that were fixed here https://github.com/Hypertopic/LaSuli/commit/ce3de29eb19e166710e0db96378b822ae6a3250f. If you can send me (in private) the way to reproduce it, I'll try to adapt the fix.

**Comment by benel** [comment]
> What do you mean "for real" ? Do you have some example of data that makes it crash ?

I open several item pages in tabs (several dozens), and start to edit topics, attributes and so on.
Minutes later, pages that are in the background got an exception (when they are refeshed).

I got the problem several time when I edited descriptions for an hour or more.

**Comment by franck-eyraud** [comment]
> If you can send me (in private) the way to reproduce it, I'll try to adapt the fix.

I think I found the way to reproduce it : load the page, remove the network connection, wait a bit (for the timeout to trigger), and the exception occurs. Because request fails, and data are empty. It does the same on v7 branch 19636f1. This can happen for instance when the computer comes back from sleep, or if wifi is lost, so I suppose it should be handled to ignore the refresh in that case. Will try to find some way to fix it.

**Comment by benel** [comment]
About the fixes (list of December, 6th), most of them are OK, but there are still browsers incompatibilities:
- [x] `TAB` and `SHIFT-TAB` works on Firefox but not on Chrome and Safari, 
- [x] `BACKSPACE` works on Firefox and Safari but not on Chrome.

Please also note that when a textbox appears, the corresponding topic should not be created yet. To rephrase this:  When ENTER is pressed while a textbox is active:
- if the textbox corresponds to an existing topic, then the topic should be renamed, else it should be created,
- a textbox should appear under the current topic (with no actual topic stored on the server).

These have two consequences:
- [x] Canceling the creation (by pressing ESC or by moving to another textbox) should not result into a noname topic,
- [x] Promoting or demoting the current topic should not empty the textbox (if the topic is still not created, the broader topic should be remembered until the creation of the current topic).

I hope this won't require to much rework...

**Comment by benel** [comment]
Please note also that before the refactoring, the following feature was implemented:

- [x] Rename a viewpoint (#41).

It doesn't seem to work after the refactoring.

**Comment by franck-eyraud** [comment]
> When ENTER is pressed while a textbox is active:
>
>  - if the textbox corresponds to an existing topic, then the topic should be renamed, else it should be created,

What if nothing has been typed in the textbox ? Should the topic be created without a name, or should this be ignored ?

**Comment by benel** [comment]
> What if nothing has been typed in the textbox ? Should the topic be created without a name, or should this be ignored ?

Topic creation without a name seems to be the better way to let understand how it works. Moreover there can be a few situations where an unamed topic whould be needed.

**Comment by franck-eyraud** [comment]
Most of the above points should now been addressed, but it might require some extra checks from you.

**Comment by benel** [comment]
> Most of the above points should now been addressed, but it might require some extra checks from you.

It feels much better at first sight. However a few problems stay:
- [ ] When you try to add topic and cancel, the local state is OK but the server is not. You can see no name topics when you consult the viewpoint again (or when you simply refresh the page).
This should be the opposite: the wannabe topic should be only on local state (until the name is validated), so when it is canceled, you only have to remove it from the local state.
- [ ] No requests are sent on removing a topic (only the local state is modified). 
- [ ] When you create a viewpoint and to try to change its name at once, you get an exception.

**Comment by franck-eyraud** [comment]
Thank you for the tests. 

The three above commits should solve the errors you pointed out (some silly code errors for the first two ones). And about the viewpoint creation, I realise that viewpoint deletion is not foreseen, is it ?

**Comment by benel** [comment]
> Thank you for the tests.

Thank *you* for the fixes :)

> I realise that viewpoint deletion is not foreseen, is it ?

As you can see [in the kanban](https://github.com/orgs/Hypertopic/projects/1), feature #60 is suggested but not planned for now. Of course it is useful, but not a priority compared to other features. This means that in the meanwhile, an administrator have to do this through the REST API.

**Comment by benel** [comment]
> feature #60 is suggested but not planned for now.

This is also a "dangerous" feature which will have to be designed carefully.

**Comment by benel** [comment]
This pull request is ready for merging!
Thanks for the good work @franck-eyraud !!!

**Pull request merged**
