### PR TITLE
Document's attributes should be in a copyright (see #570).

### LINKED ISSUE #570: Document's attributes should be in a copyright
### Description

The informations about de author and the date would be moved in a copyright under the picture. 

#### What is the valuable outcome that cannot be achieved because of this bug?

The user can see the more valuable informations quickly.

#### For which stakeholder (people, role, project, domain) is it important?

Important for users who are visiting.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

### PR DESCRIPTION
**Pull request by Couapy**
Co-authored-by: LucasJeanpierre <lulu.jeanpierre@gmail.com>
Co-authored-by: Paul Hego <paul.hego@utt.fr>
Co-authored-by: Thomas Raymond <thomas.raymond@utt.fr>

## Content

This adds a scenario for issue https://github.com/Hypertopic/Porphyry/issues/570.

---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    - [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Comment by maxime-huyghe** [comment]
The scenario should specify that the user uses a phone.

**Review by benel — CHANGES_REQUESTED** [review]
Thank you for this interesting contribution.

Please take note of the following requirements : 

1. When pull requests are ready, move from `draft` to `active`,

2. The commit `FIX: Make the mobile scenario more precise` doesn't follow the (it is not a "fix" of the software (to be reported in the changes of a release) but a correction of a preceding commit. Please modify the preceding commit to include this one.

**Review by benel — CHANGES_REQUESTED** [review]
## Historique

- [x] Je n'avais pas fait attention, mais il y a un problème dans le titre de vos commits.
Le titre doit décrire ce que ça fait. Vous avez changé l'affichage des attributs et non l'ordre, non ?
Du coup, c'est le nouveau nom du ticket que vous devez utiliser ("Document's attributes should be in a copyright") et pas l'ancien ("Item page should be sorted differently on mobile page").
- [x] À l'occasion, pensez à renommer aussi la pull request. C'est important pour documenter le projet.

## Comportement

J'ai pu tester l'intégration de votre code, les tests passent bien. 👌🏼 
J'ai testé à la main, ça fonctionne dans la plupart des cas 👌🏼 

- [ ] Attention, à prendre en compte le cas de [la photographie en noir et blanc](http://localhost:3000/item/Vitraux%20-%20Recensement/d4dd4b9af975a07ecd0331307db8ca24daad7535) : elle n'a pas d'auteur mais elle a une date (qui plus est dans un format spécial mais qui est standard). 
- [ ] le format habituel pour un "crédit photographique" est "© Auteur, Année". Il faudrait donc parser la date (qui peut avoir différents formats) pour ne garder que l'année. Là aussi, attention à ce que ça fonctionne pour le cas précédent.

Merci d'avance

**Comment by maxime-huyghe** [comment]
@Couapy could you rename the PR to "Document's attributes should be in a copyright", please?

**Comment by maxime-huyghe** [comment]
Renamed the commits.

**Pull request merged**
