### PR TITLE
FIX: The picture of a shared item is not visible on a Facebook publication (see #380)

### PR DESCRIPTION
**Pull request by LSauter68140**
Co-authored-by: Toine-prog <62764276+Toine-prog@users.noreply.github.com>
Co-authored-by: YaellePihan <yaelle.pihan@gmail.com>

## Content

Now with FB sharing button from disqus we can share a stained glass's Photo with a thumbnail on FB
---

## Checklist

Please check that your pull request is correct:

- Each commit:
    - [ x] corresponds to a contribution that should be notified to users,
    - [x] does not generate new errors or warnings at compile or test time,
    - [x] must be attributed to its real authors (with correct GitHub IDs and [correct syntax for multiple authors](https://help.github.com/articles/creating-a-commit-with-multiple-authors/)).
- The title of a commit should:
    -    [x] begin with a contribution type
        - `FEATURE` for a behaviour allowing a user to do something new,
        - `FIX` for a behaviour which has been changed in order to meet user’s expectations,
        - `SCENARIO` for examples showing a given behaviour,
        - `TEST` when it concerns an acceptance test of a given behaviour,
        - `PROCESS` for a change in the way the software is built, tested, deployed,
        - `DOC` when it concerns only internal documentation (however it is better to combine it with the contribution that required this documentation change),
    - [x] be followed by a colon (`:`) with one space after and no space before,
    - [x] be followed by a title (written in English) as short, as user-centered and as explicit as possible
        - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
        - If it is a fix, the title must describe the intended behavior (with `should`).
    - [x] ends with a reference to the corresponding ticket with the following syntax:
        - `(closes #xx)` if xx is a feature ticket (and the commit is a complete implementation),
        - `(fixes #xx)` if xx is a fix ticket (and the commit is a complete fix),
        - `(see #xx)` otherwise,
- Each committed line is:
    - [x] useful (it would not work if removed)
        - if it is a comment line, its information could not be conveyed by better variables and function naming, better code structuring, or better commit message,
    - [x] related to this very contribution (feature, fix...),
    - [x] in English (with the exception of Gherkin scenarios in French and resulting steps),
    - [x] without any typo in variable, class or function names,
    - [x] correctly indented (spaces rather than tabs, same number of characters as in the rest of the file).

### CODE REVIEW

**Comment by benel** [comment]
@LSauter68140 @Toine-prog @YaellePihan 

Super pour l'historique !

Je n'avais pas remarqué, c'est fait exprès que `null` soit une chaîne de caractère ?

**Comment by LSauter68140** [comment]
> Je n'avais pas remarqué, c'est fait exprès que `null` soit une chaîne de caractère ?

Les paramètres de l'objet ``config`` du  composant ``DiscussionEmbed`` ne peuvent prendre en compte que des ``string`` (si on met un ``null`` de type null cela renvera une erreur)  or parfois le temps de fetch avec le argos est plus long que celui du render avec react, donc on a ``props.item`` qui est encore null ce qui entraine un erreur. C'est pour ça que j'ai ajouté une condition sur ces éléments là. Le fait d'avoir mis un ``string`` "null" est purement arbitraire, on aurait très bien pu renvoyer une ``string`` vide, mais j'ai pensé que c'était plus clair de le faire comme ceci.

**Comment by benel** [comment]
OK. Merci de cette explication @LSauter68140.

**Comment by benel** [comment]
J'ai intégré votre code à la branche principale ! Bravo ! @LSauter68140 @Toine-prog @YaellePihan


Par contre, le titre n'a pas l'air de passer (en comparaison d'un partage à la main) : 

Capture d’écran 2021-06-10 à 12 02 39
Capture d’écran 2021-06-10 à 12 03 16

Avez-vous expérimenté cela également ?

**Pull request merged**
