### PR TITLE
Add and edit item's attributes

### PR DESCRIPTION
**Pull request by franck-eyraud**
This pull requests solves issue #140, and implements #29 

Work in progress...

### CODE REVIEW

**Comment by benel** [comment]
Wouldn't be the code a bit smaller (in lines of code) and easier to read with controlled components? 

See:
- [React documentation about forms processing](https://reactjs.org/docs/forms.html),
- [example in LaSuli](https://github.com/Hypertopic/LaSuli/pull/68/files#diff-669788500c5801aa9e77df0f658f0722).

**Comment by franck-eyraud** [comment]
Thanks for the suggestion, I didn't know about the controlled components. But I don't get where it would help in this situation. It seems that it more or less relies on keeping trace of the inserted value in the state, which I don't do indeed, but anyway instead of reading the value from the input directly, if I would read it from the state, it will not reduce much the number of lines. Unless

The relatively high number of lines seems to me to be due to the different reactions depending on the value (hide/show the button, change its content, ...)

You are right that by considering these aspects, the code could be improved a bit, but I was wondering if you were meaning something more powerful that I don't see.

**Comment by benel** [comment]
I agree that it is not a great improvement... And I suspect it requires a tiny bit more computing power. 

However, I find the code easier to understand... But maybe it’s me... ?

**Comment by benel** [comment]
> Work in progress...

Here is a little roadmap:

- [x] place holders with two states,
- [x] french typography and light style (`attribut : valeur` with low case and spaces),
- [x] buttons coherence to add something (and only visible on focus),
- [x] no form reset button (escape would be enough),
- [ ] coherence between attribute edition and topic rename in viewpoint edition (on place with one or two clicks).

**Comment by benel** [comment]
By the way, why did the attribute delete button move?

**Comment by franck-eyraud** [comment]
> I agree that it is not a great improvement... And I suspect it requires a tiny bit more computing power. However, I find the code easier to understand... But maybe it’s me... ?

No, I don't think it's you. I got your point after having given a closer look. I missed an important point on the first place, it is the fact that the value of the input is forced at render time (value={this.state.value}).

Do you think that last commit makes it better ?

**Comment by franck-eyraud** [comment]
>     * place holders with two states

What do you mean by this ?

> By the way, why did the attribute delete button move?

I don't remember exactly why I found it more logical. Maybe so that it doesn't appear at the same time than the edit button, plus programmer's idea that you edit the value, and remove the attribue, but it is probably not that logical for the user.
Do you think it is better to move it back ?

**Comment by benel** [comment]
> Do you think that last commit makes it better ?

Indeed. The code is shorter and easier to understand.

> > place holders with two states

> What do you mean by this ?

It was just a reference to [the mockup I did earlier](https://user-images.githubusercontent.com/597307/53436941-9ec89c80-39fc-11e9-97ba-619702e27fda.jpeg). For example the place holder of a new attribute is `Ajouter un attribut et une valeur` and is changed into `attribut : valeur` once it has the focus.

**Comment by franck-eyraud** [comment]
> It was just a reference to [the mockup I did earlier](https://user-images.githubusercontent.com/597307/53436941-9ec89c80-39fc-11e9-97ba-619702e27fda.jpeg). For example the place holder of a new attribute is `Ajouter un attribut et une valeur` and is changed into `attribut : valeur` once it has the focus.

OK, I got it, sorry. I did it for the attribute.

>     * buttons coherence to add something (and only visible on focus),

I have a small issue with button visible only focus : if it disappears on focus lost (blur event), there is not enough time to click on it to submit the form... do you have an idea of another dynamic ? For now, it is visible if the entered value is correct.

**Comment by franck-eyraud** [comment]
> I have a small issue with button visible only focus : if it disappears on focus lost (blur event), there is not enough time to click on it to submit the form... do you have an idea of another dynamic ? For now, it is visible if the entered value is correct.

Maybe I found a way, let me know what you think of last push.

**Comment by franck-eyraud** [comment]
Last push addresses these [comments](https://github.com/Hypertopic/Porphyry/issues/140#issuecomment-478046216).

**Comment by benel** [comment]
Clicking on the button to add the attribute does not work anymore on Firefox and Safari (but it works on Chrome). https://streamable.com/qtuwn

**Comment by franck-eyraud** [comment]
> Clicking on the button to add the attribute does not work anymore on Firefox and Safari (but it works on Chrome). https://streamable.com/qtuwn

Thank you for the notification, it wasn't occurring on Firefox Linux, it seems only on MacOSX. The timeout delay to hide button was too small for it. I wonder if this method to hide the button is the good one to have a correct behaviour for sure everywhere...

By the way, we should apply the same "button hide" on attribute edit also, right ?

**Comment by benel** [comment]
>> By the way, why did the attribute delete button move?

> I don't remember exactly why I found it more logical. Maybe so that it doesn't appear at the same time than the edit button, plus programmer's idea that you edit the value, and remove the attribue, but it is probably not that logical for the user.

I see your point... But in the whole interface, every action is at the rightside of the related object, therefore in the current version I personally understood your edit button as related to the attribute name (not to the attribute value). 

> Do you think it is better to move it back ?

Therefore I would find more logical to find both buttons at the right:

    attribute : value EDIT DEL

In this order, because you're right, `EDIT` is related to `value` while `DEL` is related to `attribute:value`.

**Comment by franck-eyraud** [comment]
OK, that makes sense. The edit button can be either close to the value at its right, or aligned to the right, close to the delete button. Do you have a preference ?

**Comment by benel** [comment]
> The edit button can be either close to the value at its right, or aligned to the right, close to the delete button. Do you have a preference ?

Even if your first proposal makes sense. A buttons group looks probably better.

**Comment by franck-eyraud** [comment]
OK, I made the change, let me know

**Comment by Kodlah** [comment]
Projet Graines d'artistes : 
Permettre d'ajouter ou de modifier les attributs d'un dessin.

**Pull request merged**
