### PR TITLE
Move topics using drag and drop

### PR DESCRIPTION
**Pull request by franck-eyraud**
This pull requests implements drag and drop to move topics. #139

Currently moves only within siblings to change their order.

It uses plain HTML5 drag and drop feature.

### CODE REVIEW

**Comment by franck-eyraud** [comment]
Is it necessary to allow to change a topic's parent with drag and drop? If yes, I'm not sure how to design UI to distinguish between changing siblings order and setting a new parent.

**Comment by benel** [comment]
> Is it necessary to allow to change a topic's parent with drag and drop. 

Indeed. 

> If yes, I'm not sure how to design UI to distinguish between changing siblings order and setting a new parent.

In similar software, depending on the drag-over mouse position, the drop zone has a different horizontal offset. 
I don’t know if it is clear...

**Comment by franck-eyraud** [comment]
> In similar software, depending on the drag-over mouse position, the drop zone has a different horizontal offset.
> I don’t know if it is clear...

Yes, it is clear, thank you for the answer. I think that above commit correctly implements this. Let me know if you find it OK.

**Comment by benel** [comment]
It works well. Well done for the good job, @franck-eyraud !
We have now a full-featured viewpoint editor!

I was a bit surprised by the location of the drop zones (esp. for siblings) and the kind of feedback (visible copy of the dragged tree and gap prepared for it), but maybe it's just because I am accustomed to OmniOutliner. We can prevalidate the feature like this and change it slightly on users' feedbacks.

**Comment by franck-eyraud** [comment]
> I was a bit surprised by the location of the drop zones (esp. for siblings) and the kind of feedback (visible copy of the dragged tree and gap prepared for it), but maybe it's just because I am accustomed to OmniOutliner. We can prevalidate the feature like this and change it slightly on users' feedbacks.

Yes, sure, this is what I had in mind. I didn't spend much time on this, giving space for improvement. The visible ghost dragged item is the default in HTML5 drag and drop, but can be overridden by a [custom image](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setDragImage) (anything more complex requires some hack, it seems...). 
About the prepared gap, since we have 2 different behaviour (drop as sibling or child) depending on mouse position, I think it is necessary to have a visual feedback of what would happen. But this can be also improved.

**Pull request merged**
